### PR TITLE
Add support to API v23

### PR DESCRIPTION
**Pull request by fjlopezs**
Add support to API v23

### CODE REVIEW

**Comment by fjlopezs** [comment]
I signed it!

**Comment by samtstern** [comment]
@elpancholopez thanks for signing the CLA.  Can you fix the merge conflicts?  Also I like the changes for the most part, what is the motivation behind changing the theme colors?

**Comment by fjlopezs** [comment]
Sorry,  I copied a few lines more by mistake.
But I had to change the basic style because as it was gave rise to the following error: "AppCompat does not support the current theme features"

**Comment by samtstern** [comment]
Also please fix merge conflicts.

**Comment by samtstern** [comment]
Closing due to age.

**Pull request closed without merging**
