### PR TITLE
Typo in README

### PR DESCRIPTION
**Pull request by karbassi**

### CODE REVIEW

**Comment by karbassi** [comment]
I signed it!

**Comment by samtstern** [comment]
@karbassi I'm not seeing your name on the signers list.  Make sure you sign with the same information you use to log in to your Github account.

**Comment by karbassi** [comment]
@samtstern It matches my github account

id 103252723096565000863

**Comment by samtstern** [comment]
This was fixed in #2, closing.  Thanks for your contribution!

**Pull request closed without merging**
